# Generated by Django 2.2.16 on 2022-03-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220311_1222'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique following',
        ),
    ]
